baseURL = 'https://julesolaye.github.io/'
publishDir = "docs"
languageCode = 'en-us'
title = "Jules Olayé's website"
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Welcome!'
homeIntroContent = """
My name is Jules Olayé. I am a Ph.D. student at Ecole Polytechnique, Palaiseau, France, working under the supervision of Marie Doumic and Milica Tomašević. I am interested in the study of mathematical models coming from biology, with both deterministic and stochastic approaches.

## Research topics
- Integro-differential equations,
- Age-dependent branching processes,
- Density estimation,
- Applications to biology.
"""


# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
#[[params.social]]
#name = "linkedin"
#url = "https://www.linkedin.com/in/jules-olay%C3%A9-92853a1aa/"


#[[params.social]]
#name = "github"
#url = "https://github.com/julesolaye"

# Main menu pages
[menu]
[[params.menu]]
name = "Home"
url = "/"

[[params.menu]]
name = "Publications"
url = "/publications"

[[params.menu]]
name = "Communications"
url = "/communications"

[[params.menu]]
name = "Resume"
url = "/resume"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
